services:
  - type: web
    name: nutrition-app
    env: docker
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: 8000
      - key: OMP_NUM_THREADS
        value: 1
      - key: OPENBLAS_NUM_THREADS
        value: 1
      - key: MKL_NUM_THREADS
        value: 1
      - key: NUMEXPR_NUM_THREADS
        value: 1
      - key: MKL_THREADING_LAYER
        value: SEQUENTIAL
      - key: MALLOC_ARENA_MAX
        value: 2